name: Build and Upload Plugin

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and Install Plugin
        run: mvn install

      - name: Upload Plugin Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-doc-maven-jar
          path: ~/.m2/repository/com/ly/smart-doc
          if-no-files-found: error

      - name: Get Artifact ID and URL
        run: |
          echo "artifact_id=${{ steps.upload-artifact.outputs.artifact-id }}" >> $GITHUB_ENV

      - name: Trigger Example Project Workflow
        env:
          MY_TOKEN: ${{ secrets.SMART_DOC_CHECK_TOKEN }}
        run: |
          echo "token=$MY_TOKEN"
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.SMART_DOC_CHECK_TOKEN }}" \
          -d "{\"event_type\":\"run-plugin\", \"client_payload\": {\"artifact_id\": \"${{ env.artifact_id }}\"}}" \
          https://api.github.com/repos/smart-doc-group/smart-doc-example-cn/dispatches
