name: Deploy to Maven Central

on:
  release:
    types: [created]

jobs:
  deploy:
    if: ${{ github.repository == 'TongchengOpenSource/smart-doc' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Deploy to Maven Central
        run: mvn deploy -P release
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
